name: Create script release
run-name: ${{ github.actor }} started a release job.
on: [push]
jobs:
  build-script-release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job started by a ${{ github.event_name }} event."
      - run: echo "Job a ${{ runner.os }} server."
      - run: echo "Job is running on repository ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "Cloning the ${{ github.repository }} repository to the build job."
      - name: Set the tag to env variable.
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Echo the release version.
        run: echo "The release version is ${{ env.RELEASE_VERSION }}"
      - name: Verify the release version format.
        run: |
          echo ${{ env.RELEASE_VERSION }} | grep -E '^[0-9]+(\.[0-9]+){2}$' >/dev/null && echo "The release version has correct format." || echo "Invalid release version format." && exit 1
