name: Create script release
run-name: ${{ github.actor }} started a release job.
on: [push]
jobs:
  Create-Script-Release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job started by a ${{ github.event_name }} event."
      - run: echo "Job a ${{ runner.os }} server."
      - run: echo "Job is running on repository ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "Cloning the ${{ github.repository }} repository to the build job."
      - name: Set the tag to env variable.
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: List the workspace for now.
        run: |
          ls ${{ github.workspace }}
      - name: List the current directory.
        run: |
          pwd
